server:
  port: 9090
spring:
  application:
    name: msvc-course

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coursesDb
    username: postgre
    password: postgre

  jpa:
    hibernate:
      dbl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http://localhost:8888

  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        default-zone: http://localhost:8761/eureka
